services:
  notedown:
    build: .
    container_name: "notedown"
    restart: always
    networks:
      - traefik_proxy
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/.data
    volumes:
      - ./data_storage:/app/.data
      - ./uploads_storage:/app/public/uploads
    ports:
      - "3000:3000"
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notedown.rule=Host(`notes.elyesghazel.ch`)"
      - "traefik.http.routers.notedown.entrypoints=https"
      - "traefik.http.routers.notedown.tls=true"
      - "traefik.http.routers.notedown.tls.certresolver=cloudflare"
      - "traefik.http.services.notedown.loadbalancer.server.port=3000"
      - "traefik.http.routers.notedown.middlewares=limit-size"

networks:
  traefik_proxy:
    external: true

