services:
  notedown:
    build: .
    container_name: "notedown"
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notedown.rule=Host(`notes.elyesghazel.ch`)"
      - "traefik.http.routers.notedown.entrypoints=https"
      - "traefik.http.routers.notedown.tls=true"
      - "traefik.http.routers.notedown.tls.certresolver=cloudflare"
      - "traefik.http.services.notedown.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true

