services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markdown-notes
    ports:
      - "3000:3000"
    volumes:
      - ./data_storage:/app/.data
      - ./uploads_storage:/app/public/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notedown.rule=Host(`notes.elyesghazel.ch`)"
      - "traefik.http.routers.notedown.entrypoints=https"
      - "traefik.http.routers.notedown.tls=true"
      - "traefik.http.routers.notedown.tls.certresolver=cloudflare"
      - "traefik.http.services.notedown.loadbalancer.server.port=80"

